### ISSUE TITLE
Vincenty inverse

### ISSUE THREAD

**Issue by sdalu** [ucnl/UCNLNav#11]
In the vincenty inverse function (I've only checked the rust code), when `cos_sq_alpha` is not different from `0.0` then `cos_sq_alpha` is set to `0.0`, it should be `cos_2_sigma_m` which is set to `0.0` according to http://www.movable-type.co.uk/scripts/latlong-vincenty.html

It would also be better to compare `cos_sq_alpha` to be less than an epsilon value than equality to `0.0`

**Comment by AlekUnderwater** [comment]
Sure it is! Thanks for improving the code. Bug is fixed in all implementations (C#, Rust, Matlab)
