### ISSUE TITLE
build_base_lines iterations

### ISSUE THREAD

**Issue by sdalu** [ucnl/UCNLNav#12]
In rust (not checked other) code, the `build_base_lines` iterate over: `0 .. (base_points.len() - 1)` and `(i+1) .. base_points.len()`
shouldn't it be: `0 .. (base_points.len() - 1)` and `(i+1) .. base_points.len() - 1` ?

**Comment by sdalu** [comment]
I supposed the range operator was the same in rust as it is in ruby (inclusive in both side)

**Comment by AlekUnderwater** [comment]
Yep, it is eqivalent to C's for (int i = 0; **i < len**; i++) not **i <= len**
