### ISSUE TITLE
Precision Threshold

### ISSUE THREAD

**Issue by Nikhal62** [ucnl/UCNLNav#2]
I have a doubt regarding the value of the precision threshold for the termination of the iteration. Why did you choose '1E-8' as the precision threshold value? Can I change it into my own value? In what perspective, you choose that value.

**Comment by AlekUnderwater** [comment]
It is just the first version of the library. 1E-8 is relatively big value for the threshold, chosen for testing purposes. It will be changed with the appropriate value in the upcoming update.
