### ISSUE TITLE
Case study for Localization algorithm

### ISSUE THREAD

**Issue by Nikhal62** [ucnl/UCNLNav#5]
Is there any case study for this localization algorithm using Nelder-Mead method to refer so that it can be implemented in some real-life scenarios? Can you please share any case study papers based on this or any other similar things with you?

**Comment by AlekUnderwater** [comment]
Here is our paper on VLBL positioning performed by TOA and Nelder-Mead optimization:
[Position Estimation of Autonomous Underwater Sensors Using the Virtual Long Baseline method](https://www.researchgate.net/publication/332946775_Position_Estimation_of_Autonomous_Underwater_Sensors_Using_the_Virtual_Long_Baseline_Method)

Actually, Nelder-Mead is just an optimization method, you can use any other method (Gradient descent for example).

If you like the library and/or find it useful, please, star this repository - more stars will help other people to find it.
